---
- name: Copy install script
  template:
    src: install_docker.sh
    dest: /home/ec2-user/install_docker.sh
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Install docker engine
  shell:
    cmd: sh install_docker.sh
    chdir: /home/ec2-user/

- name: Download and install docker-compose binary
  shell: |
    curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    chown -R ec2-user:ec2-user /usr/local/bin/
  args:
    warn: no
  become: yes
